# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b54c1617472c8fa1ad8eb6c4b23ff76f0cf662d6b1d528d62f185f4dcd9bd9e14ba6784ab457a0c85e1574722f80704267484bce7b1f14a2f2e1d47aeba6514

test:
  secret_key_base: 2f52a8f8cd70e69e5e18db632f03e67dacc660a80dc54c82741dca2f064d1bc33b0cb604bf9416197cd70b7733e43d751fa2b48fe13927775a7fbad70dd5c2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
